<a href="https://colab.research.google.com/github/chminPark/ml-python/blob/master/Project_skeleton.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Pytorch로 개발하기 위한 Library
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import matplotlib.pyplot as plt

import numpy as np

torch.__version__

'2.1.0+cu118'

In [ ]:
!gdown --id 1L3aXv9A2bn8G9orLqjVWOE_1OY4ycdjs
!mkdir 'chip_data'
!unzip -q chip_data.zip -d chip_data
!rm chip_data.zip

/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1L3aXv9A2bn8G9orLqjVWOE_1OY4ycdjs
To: /content/chip_data.zip
100% 83.5M/83.5M [00:05<00:00, 16.3MB/s]
와이어끊어짐/Sat Nov 25 15-02-18.jpg:  mismatching "local" filename (ьЩАьЭ┤ьЦ┤ыБКьЦ┤ьзР/Sat Nov 25 15-02-18.jpg),
         continuing with "central" filename version
와이어끊어짐/Sat Nov 25 15-02-19.jpg:  mismatching "local" filename (ьЩАьЭ┤ьЦ┤ыБКьЦ┤ьзР/Sat Nov 25 15-02-19.jpg),
         continuing with "central" filename version
와이어끊어짐/Sat Nov 25 15-02-20.jpg:  mismatching "local" filename (ьЩАьЭ┤ьЦ┤ыБКьЦ┤ьзР/Sat Nov 25 15-02-20.jpg),
         continuing with "central" filename version
와이어끊어짐/Sat Nov 25 15-02-21.jpg:  mismatching "local" filename (ьЩАьЭ┤ьЦ┤ыБКьЦ┤ьзР/Sat Nov 25 15-02-21.jpg),
         continuing with "central" filenam

# CSV 읽어 오는 코드생성

In [ ]:
import csv
import os
import pandas as pd

dict_map = {
        'crack, scratch, stamp' : 1,
        'particle' : 2,
        'titled' : 3,
        "와이어끊어짐" : 4,
        "정상": 0
    }

def build_csv(directory_string, output_csv_name):

    directory = directory_string
    class_list = os.listdir(directory)
    class_list.sort()

    ## 채워넣으세요

    return

folder = ##
build_csv(folder, 'train.csv')
all_df = ##


In [ ]:
all_df

file_name  \
0    Sat Nov 25 15-20-27.jpg   
1    Sat Nov 25 15-20-32.jpg   
2    Sat Nov 25 13-22-27.jpg   
3    Sat Nov 25 15-24-11.jpg   
4    Sat Nov 25 15-24-15.jpg   
..                       ...   
850  Sat Nov 25 14-05-57.jpg   
851  Sat Nov 25 14-08-38.jpg   
852  Sat Nov 25 13-44-32.jpg   
853  Sat Nov 25 13-54-56.jpg   
854  Sat Nov 25 13-34-39.jpg   

                                             file_path             class_name  \
0    /content/chip_data/crack, scratch, stamp/Sat N...  crack, scratch, stamp   
1    /content/chip_data/crack, scratch, stamp/Sat N...  crack, scratch, stamp   
2    /content/chip_data/crack, scratch, stamp/Sat N...  crack, scratch, stamp   
3    /content/chip_data/crack, scratch, stamp/Sat N...  crack, scratch, stamp   
4    /content/chip_data/crack, scratch, stamp/Sat N...  crack, scratch, stamp   
..                                                 ...                    ...   
850      /content/chip_data/정상/Sat Nov 25 14-05-57.jpg                     정상   
851      /content/chip_data/정상/Sat Nov 25 14-08-38.jpg                     정상   
852      /content/chip_data/정상/Sat Nov 25 13-44-32.jpg                     정상   
853      /content/chip_data/정상/Sat Nov 25 13-54-56.jpg                     정상   
854      /content/chip_data/정상/Sat Nov 25 13-34-39.jpg                     정상   

     class_index  
0              1  
1              1  
2              1  
3              1  
4              1  
..           ...  
850            0  
851            0  
852            0  
853            0  
854            0  

[855 rows x 4 columns]

# Custom데이터를 활용하기 위한 Dataset을 선언
- pytorch의 `dataloader`를 이용하기 위해서는 `torch.utils.data.Dataset` 클래스를 상속한 클래스의 선언이 필요하다.
- 클래스 내에 `__init__`, `__getitem__`, `__len__`의 3개의 메소드를 선언하여 오버라이드한다.

In [ ]:
import cv2
import torch
from torch.utils.data import Dataset

class semiconductorDataset(Dataset): # inheritin from Dataset class

    def __init__(self, csv_file, root_dir="", transform=None):
       ## 채워넣으세요

    def __len__(self):
        return len(self.annotation_df) # return length (numer of rows) of the dataframe


    def __getitem__(self, idx):

        ## 채워넣으세요
        return image, class_name, class_index

In [ ]:
from torchvision import transforms
import matplotlib.pyplot as plt
import random

transform = transforms.Compose([
      ## 채워넣으세요
 ])

transform_test = transforms.Compose([
    ## 채워넣으세요
])


# Train Test 데이터셋 분류

In [ ]:
all_df['class_index'].unique()

array([1, 2, 3, 4, 0])

In [ ]:
from sklearn.model_selection import train_test_split


train, test = ## train_test_split을 이용해서 all_df 를 train과 test 용으로 나누세요
train['class_index'].value_counts(), test['class_index'].value_counts()

## 각각 csv로 생성
train.to_csv("train.csv", index=0)
test.to_csv("test.csv", index=0)

# 데이터셋 선언
dataset = semiconductorDataset(csv_file='train.csv', root_dir="", transform=transform)
test_dataset = semiconductorDataset(csv_file='test.csv', root_dir="", transform=transform_test)

In [ ]:
from torch.utils.data import random_split

train_len = int(len(dataset) * 0.8)
val_len = len(dataset) - train_len

train_dataset, val_dataset = ## 실습 : 위에 선언한 dataset을 train_dataset과 val_dataset으로 나누세요
len(train_dataset), len(val_dataset)


In [ ]:
pd.read_csv("train.csv")

file_name  \
0    Sat Nov 25 15-17-34.jpg   
1    Sat Nov 25 15-38-05.jpg   
2    Sat Nov 25 14-17-43.jpg   
3    Sat Nov 25 15-24-12.jpg   
4    Sat Nov 25 14-05-24.jpg   
..                       ...   
679  Sat Nov 25 13-28-25.jpg   
680  Sat Nov 25 15-15-11.jpg   
681  Sat Nov 25 15-41-02.jpg   
682  Sat Nov 25 15-25-58.jpg   
683  Sat Nov 25 15-38-40.jpg   

                                             file_path             class_name  \
0    /content/chip_data/와이어끊어짐/Sat Nov 25 15-17-34.jpg                 와이어끊어짐   
1    /content/chip_data/particle/Sat Nov 25 15-38-0...               particle   
2        /content/chip_data/정상/Sat Nov 25 14-17-43.jpg                     정상   
3    /content/chip_data/crack, scratch, stamp/Sat N...  crack, scratch, stamp   
4        /content/chip_data/정상/Sat Nov 25 14-05-24.jpg                     정상   
..                                                 ...                    ...   
679      /content/chip_data/정상/Sat Nov 25 13-28-25.jpg                     정상   
680  /content/chip_data/와이어끊어짐/Sat Nov 25 15-15-11.jpg                 와이어끊어짐   
681  /content/chip_data/particle/Sat Nov 25 15-41-0...               particle   
682  /content/chip_data/crack, scratch, stamp/Sat N...  crack, scratch, stamp   
683  /content/chip_data/particle/Sat Nov 25 15-38-4...               particle   

     class_index  
0              4  
1              2  
2              0  
3              1  
4              0  
..           ...  
679            0  
680            4  
681            2  
682            1  
683            2  

[684 rows x 4 columns]

# Batch 단위 학습을 위한 DataLoader 선언
 - Dataset내부의 샘플들을 batch 크기로 추출
 - Batch Size는 1step에 들어간 데이터의 개수
 - Epoch 마다 데이터를 섞어(Shuffle) Overfitting을 방지
 - 병렬처리를 지원하여 데이터 검색 속도를 향상


In [ ]:
train_dataloader = ## dataloader를 선언한다. Batch크기는 10, shuffle=True
val_dataloader = ## dataloader를 선언한다. Batch크기는 10, shuffle=False
test_dataloader = ## dataloader를 선언한다. Batch크기는 10, shuffle=False

# VGG6를 이용하여 학습을 수행한다
![](https://drive.google.com/uc?export=view&id=1vLrvhxczx1ZCOH05cxzzESylaOaF1Uj2)


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt

class VGG_BatchNormTorch(nn.Module):
    ## VGG구조를 가지고 온다.

In [ ]:
class EarlyStopping:
    """Early stops the training if validation loss doesn't improve after a given patience."""
    def __init__(self, patience=7, verbose=False, delta=0, path='checkpoint.pt', trace_func=print):
        """
        Args:
            patience (int): How long to wait after last time validation loss improved.
                            Default: 7
            verbose (bool): If True, prints a message for each validation loss improvement.
                            Default: False
            delta (float): Minimum change in the monitored quantity to qualify as an improvement.
                            Default: 0
            path (str): Path for the checkpoint to be saved to.
                            Default: 'checkpoint.pt'
            trace_func (function): trace print function.
                            Default: print
        """
        self.patience = patience
        self.verbose = verbose
        self.counter = 0
        self.best_score = None
        self.early_stop = False
        self.val_loss_min = np.Inf
        self.delta = delta
        self.path = path
        self.trace_func = trace_func
    def __call__(self, val_loss, model):

        score = -val_loss

        if self.best_score is None:
            self.best_score = score
            self.save_checkpoint(val_loss, model)
        elif score < self.best_score + self.delta:
            self.counter += 1
            self.trace_func(f'EarlyStopping counter: {self.counter} out of {self.patience}')
            if self.counter >= self.patience:
                self.early_stop = True
        else:
            self.best_score = score
            self.save_checkpoint(val_loss, model)
            self.counter = 0

    def save_checkpoint(self, val_loss, model):
        '''Saves model when validation loss decrease.'''
        if self.verbose:
            self.trace_func(f'Validation loss decreased ({self.val_loss_min:.6f} --> {val_loss:.6f}).  Saving model ...')
        torch.save(model.state_dict(), self.path)
        self.val_loss_min = val_loss

In [ ]:
def train(model, data_loader, val_loader, early_stopping, criterion, optimizer, n_epoch):
  ### 실습 : Early stop을 수행하는 학습함수를 작성한다.


In [ ]:
def eval(model, data_loader):
  #### 실습 : 평가를 위해서는 eval()을 선언
  model.eval()
  total = 0
  correct = 0

  preds = []
  trues = []
  #### 실습 : Gradient를 타지 않아야 한다
  with torch.no_grad():
    for images, _, labels in data_loader:
      images, labels = images.cuda(), labels.cuda()
      outputs = model(images)
      _, predicted = torch.max(outputs, 1)
      total += labels.size(0)
      correct += (predicted == labels).sum().item()
      preds.append(predicted.detach().cpu().numpy())
      trues.append(labels.detach().cpu().numpy())

    accuracy = 100 * correct / total

  print('Test Accuracy: {}%'.format(accuracy))
  return preds, trues


In [ ]:
def reset_seed(seed):
    torch.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)

In [ ]:
reset_seed(2020)
criterion = nn.CrossEntropyLoss()
vgg_batchnorm_model = ## 모델을 선언해서 gpu로 올린다.
optimizer = # 최적화 함수 선언

earlystop = EarlyStopping(patience=7)
train(## 학습을 위한 인지 전달)

Epoch 1, train_loss = 1.347, val_loss = 1.410
Epoch 2, train_loss = 1.223, val_loss = 1.211
Epoch 3, train_loss = 1.170, val_loss = 1.191
EarlyStopping counter: 1 out of 7
Epoch 4, train_loss = 1.129, val_loss = 1.621
EarlyStopping counter: 2 out of 7
Epoch 5, train_loss = 1.018, val_loss = 1.261
Epoch 6, train_loss = 0.955, val_loss = 1.024
EarlyStopping counter: 1 out of 7
Epoch 7, train_loss = 0.834, val_loss = 1.885
Epoch 8, train_loss = 0.784, val_loss = 0.959
EarlyStopping counter: 1 out of 7
Epoch 9, train_loss = 0.721, val_loss = 1.178
Epoch 10, train_loss = 0.629, val_loss = 0.787
EarlyStopping counter: 1 out of 7
Epoch 11, train_loss = 0.535, val_loss = 1.042
Epoch 12, train_loss = 0.532, val_loss = 0.644
EarlyStopping counter: 1 out of 7
Epoch 13, train_loss = 0.478, val_loss = 1.564
EarlyStopping counter: 2 out of 7
Epoch 14, train_loss = 0.434, val_loss = 1.070
EarlyStopping counter: 3 out of 7
Epoch 15, train_loss = 0.439, val_loss = 0.814
EarlyStopping counter: 4 out of 

# 정확도를 평가해 봅시다
* 데이터가 너무 적어서 평가 데이터에 대한 정확도를 봅니다

In [ ]:
## 학습데이터에 대한 평가를 수행한다.
preds_r, trues_r = eval(vgg_batchnorm_model, train_dataloader)

Test Accuracy: 76.96526508226691%


In [ ]:
preds, trues = ## 평가 데이터에 대한 평가를 수행한다.

Test Accuracy: 64.32748538011695%


In [ ]:
prediction_label = np.stack(preds[:-1]).flatten()
test_labels = np.stack(trues[:-1]).flatten()
prediction_label, test_labels

(array([1, 3, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 4, 1, 0, 4, 0, 4, 1, 3,
        2, 4, 1, 4, 0, 3, 0, 0, 1, 4, 1, 1, 0, 4, 3, 4, 1, 1, 0, 0, 1, 0,
        1, 0, 0, 0, 1, 1, 3, 0, 4, 4, 3, 1, 2, 0, 1, 4, 1, 0, 0, 3, 3, 4,
        2, 4, 0, 1, 4, 1, 1, 0, 1, 0, 1, 0, 0, 0, 4, 1, 0, 4, 4, 0, 1, 1,
        4, 0, 1, 0, 0, 4, 1, 4, 0, 3, 4, 0, 0, 0, 4, 4, 4, 4, 4, 1, 0, 1,
        0, 1, 0, 4, 0, 4, 0, 1, 3, 1, 0, 1, 4, 4, 1, 1, 4, 0, 1, 1, 4, 0,
        3, 1, 0, 3, 1, 1, 3, 4, 0, 4, 4, 1, 4, 4, 0, 0, 0, 3, 1, 4, 0, 1,
        1, 1, 1, 4, 0, 0, 3, 0, 3, 1, 4, 0, 1, 0, 0, 4]),
 array([0, 0, 0, 1, 0, 0, 1, 3, 0, 1, 0, 0, 1, 0, 0, 2, 0, 2, 0, 2, 2, 3,
        2, 4, 0, 0, 0, 3, 0, 0, 1, 4, 1, 0, 0, 2, 2, 4, 1, 1, 0, 0, 1, 0,
        3, 0, 0, 0, 1, 0, 3, 0, 4, 2, 0, 0, 2, 0, 0, 4, 0, 0, 0, 3, 3, 4,
        2, 4, 0, 0, 0, 0, 3, 0, 1, 0, 1, 0, 0, 0, 2, 0, 0, 4, 2, 0, 0, 1,
        0, 0, 1, 0, 0, 2, 1, 4, 0, 3, 4, 0, 0, 1, 0, 0, 4, 2, 4, 0, 0, 1,
        0, 1, 0, 4, 0, 0, 0, 0, 0, 1, 0, 0, 4, 4, 3, 0

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(test_labels, prediction_label))

              precision    recall  f1-score   support

           0       0.95      0.60      0.73        92
           1       0.46      0.96      0.62        25
           2       1.00      0.17      0.29        18
           3       0.50      0.53      0.52        15
           4       0.49      1.00      0.66        20

    accuracy                           0.65       170
   macro avg       0.68      0.65      0.56       170
weighted avg       0.79      0.65      0.64       170



# [추가] Ensemble을 수행한다.