<a href="https://colab.research.google.com/github/chminPark/ml-python/blob/master/%EC%8B%A4%EC%8A%B5_pytorch%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# torch library를 load 합니다
import torch

In [ ]:
torch.__version__

'2.1.0+cu118'

# 행렬 덧셈과 뺄샘

In [ ]:
# 4 x 3 크기의 Matrix를 생성합니다.
A = torch.arange(1,13)
print(A)
# Matrix 형태로 크기를 변경해 주는 것은 view로 가능합니다.
A = A.view(3,4)
A

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])


tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [ ]:
# arange 는 한번에 만드는 것을 지원하지 않습니다.
# random 번호로 생성하면 한번에 만들 수 있습니다.
torch.rand(3,4)

tensor([[0.0042, 0.6828, 0.2433, 0.2708],
        [0.2774, 0.1845, 0.3914, 0.6545],
        [0.1044, 0.3427, 0.2952, 0.9993]])

In [ ]:
# 직접 만들어 볼수도 있습니다.
B = torch.Tensor([[0,0,0,0], [1,1,1,1], [2,2,2,2]])
B

tensor([[0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.]])

In [ ]:
# 더하기 연산
A+B

tensor([[ 1.,  2.,  3.,  4.],
        [ 6.,  7.,  8.,  9.],
        [11., 12., 13., 14.]])

In [ ]:
# 빼기연산
A-B

tensor([[ 1.,  2.,  3.,  4.],
        [ 4.,  5.,  6.,  7.],
        [ 7.,  8.,  9., 10.]])

In [ ]:
A+1


tensor([[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13]])

In [ ]:
B * 2

tensor([[0., 0., 0., 0.],
        [2., 2., 2., 2.],
        [4., 4., 4., 4.]])

In [ ]:
# Element wise multiplication
A * B

tensor([[ 0.,  0.,  0.,  0.],
        [ 5.,  6.,  7.,  8.],
        [18., 20., 22., 24.]])

In [ ]:
1/A

tensor([[1.0000, 0.5000, 0.3333, 0.2500],
        [0.2000, 0.1667, 0.1429, 0.1250],
        [0.1111, 0.1000, 0.0909, 0.0833]])

In [ ]:
A / 2

tensor([[0.5000, 1.0000, 1.5000, 2.0000],
        [2.5000, 3.0000, 3.5000, 4.0000],
        [4.5000, 5.0000, 5.5000, 6.0000]])

# Concatenation

In [ ]:
batch_size, N, K = 3, 10, 256

x = torch.rand(batch_size, N, K) # [batch_size, N, K]
y = torch.rand(batch_size, N, K) # [batch_size, N, K]

### Cat 은 지정한 차원에 대해 값을 붙여줌(Concatenation)
output1 = torch.cat([x,y], dim=1) #[batch_size, N+N, K]
output2 = torch.cat([x,y], dim=2) #[batch_size, N, K+K]

print(x.shape)
output1.shape, output2.shape

torch.Size([3, 10, 256])


(torch.Size([3, 20, 256]), torch.Size([3, 10, 512]))

# Stack

In [ ]:
batch_size, N, K = 3, 10, 256

x = torch.rand(batch_size, N, K) # [batch_size, N, K]
y = torch.rand(batch_size, N, K) # [batch_size, N, K]

### Stack은 지정하는 차원으로 확장하여 Tensor를 쌓아줌
output = torch.stack([x,y], dim=1) #[batch_size, 2, N, K]
x.shape, output.shape

(torch.Size([3, 10, 256]), torch.Size([3, 2, 10, 256]))

# Squeeze

In [ ]:
## Squeeze 는 차원이 1인 차원을 제거해줌
x = torch.rand(3, 1, 20, 128)
y = x.squeeze() #[3, 1, 20, 128] -> [3, 20, 128]
x.shape, y.shape

(torch.Size([3, 1, 20, 128]), torch.Size([3, 20, 128]))

In [ ]:
## Squeeze 는 차원이 1인 차원을 제거해줌
x = torch.rand(1, 1, 20, 128)
print(x.shape)
x = x.squeeze() # [1, 1, 20, 128] -> [20, 128]
print(x.shape)

torch.Size([1, 1, 20, 128])
torch.Size([20, 128])


torch.Size([1, 20, 128])

In [ ]:
## 제거할 차원을 고정!
x2 = torch.rand(128, 1, 20, 1)
print(x2.shape)

x2 = x2.squeeze(dim=1) # [1, 1, 20, 128] -> [1, 20, 128]
x2.shape

torch.Size([128, 1, 20, 1])


torch.Size([128, 20, 1])

In [ ]:
x2.squeeze().shape

torch.Size([128, 20])

# Unsqueeze

In [ ]:
## Unsqueeze는 1인 차원을 생성하는 함수
import torch

x = torch.rand(3, 20, 128)
x = x.unsqueeze(dim=1) #[3, 20, 128] -> [3, 1, 20, 128]
x.shape

torch.Size([3, 1, 20, 128])

In [ ]:
# Unsqueeze는 차원을 생성할 위치를 명확히 지정해야 한다.
x.unsqueeze()

TypeError: ignored